palette = "catppuccin_mocha"

# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

format = """
$directory $nix_shell$git_branch$git_commit$git_status$git_state\
$fill \
$python\
$c\
$rust\
$java\
$golang\
$lua 
$character
"""

[fill]
symbol = ' '

[character]
success_symbol = "[❯](bold fg:green) "
error_symbol = "[❯](bold fg:red) "

[nix_shell]
format = '[$symbol(\($state$name\))]($style) '
symbol = '[ ](#88c8fc)' # there is a flake symbol inside. try to highlight using mouse
pure_msg = '[ ](subtext0)'
impure_msg = '[ ](subtext0)'

[git_branch]
format = "on [$symbol $branch(:$remote_branch)](fg:teal) "
style = "bg: green"
symbol = "[󰘬](text)"
truncation_length = 6
truncation_symbol = ".."

[git_commit]
format = '[\($hash$tag\)]($style) '
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
format = '[$all_status$ahead_behind]($style) '
conflicted = '󰘭'
ahead = '[](sky)'
behind = '[](red)'
stashed = "[ ](subtext0)"
modified = '[ ](red)'
staged = '[ ](green)'
diverged = '[󰹺](yellow)'

[line_break]
disabled = false

[directory]
read_only = "  "
style = "fg:sapphire"
truncation_length = 2
format = '[$path]($style)'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
version_format = 'v${major}.${minor}'

[golang]
symbol = " "
style = "bold sapphire"
version_format = 'v${major}.${minor}'
format = '\[[$symbol($version)]($style)\]'
detect_extensions = ['go', 'templ']

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'
version_format = 'v${major}.${minor}'

[rust]
symbol = "󱘗 "
version_format = 'v${major}.${minor}'
style = "fg:peach"
format = '\[[$symbol($version)]($style)\]'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
