palette = "catppuccin_mocha"

# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

format = """
$directory $git_branch\
$python\
$c\
$rust\
$java\
$golang\
$lua
$character
"""

[fill]
symbol = ' '

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[❯](bold fg:green) "
error_symbol = "[❯](bold fg:red) "

[git_branch]
style = "bg: green"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = "on [$symbol $branch(:$remote_branch) ](fg:teal)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 "
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " ✍️ "
deleted = " 🗑 "

[line_break]
disabled = false

[directory]
read_only = "  "
style = "fg:sapphire"
truncation_length = 2
format = '[$path]($style)'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
version_format = 'v${major}.${minor}'

[golang]
symbol = " "
style = "bold sapphire"
version_format = 'v${major}.${minor}'
format = '\[[$symbol($version)]($style)\]'
detect_extensions = ['go', 'templ']

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'
version_format = 'v${major}.${minor}'

[rust]
symbol = "󱘗 "
version_format = 'v${major}.${minor}'
style = "fg:peach"
format = '\[[$symbol($version)]($style)\]'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
