{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    alsa-utils
    brightnessctl
    cronie
    evince
    ffmpegthumbnailer
    file-roller
    gparted
    hyprsunset
    hyprsysteminfo
    kitty
    lsof
    lxqt.lxqt-policykit
    microsoft-edge
    nixos-firewall-tool
    pavucontrol
    unzip
    usbutils
    vim
    vlc
    wezterm
    wget
    wl-clipboard
    xdg-user-dirs
    xfce.thunar
    xfce.thunar-archive-plugin
    xfce.thunar-media-tags-plugin
    xfce.thunar-volman
    xfce.tumbler
    zip
  ];
}
